spring.application.name=juniecm
spring.datasource.url=jdbc:sqlite:juniecm.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Liquibase
spring.liquibase.change-log=classpath:liquibase/db.changelog-master.xml
